version: "3"

services:
  web:
    build: .
    image: apache-php
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: "computadora_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin12345"
      MYSQL_ROOT_PASSWORD: "admin12345"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/create.sql
